### ISSUE TITLE
Segmentation Fault Error Running CrystalFormer Sampling

### ISSUE THREAD

**Issue by Osgood001** [deepmodeling/CrystalFormer#5]
**Description:**

I am experiencing a `Segmentation fault` when running the CrystalFormer script on my CUDA 12.1 environment. Below are the steps I followed and the relevant script outputs:

**Expected Behavior:**
- The script should execute without errors, completing its intended task.

**Actual Behavior:**
- After correcting the script by removing the unrecognized option, the script still resulted in a `Segmentation fault`.

```bash
python /home/CrystalFormer/src/main.py --optimizer none --test_path /home/CrystalFormer/data/mini.csv --restore_path /data/model/epoch_003800.pkl --spacegroup 160 --num_samples 1000  --batchsize 1000 --temperature 1.0
2024-06-27 16:41:50.440252: W external/xla/xla/service/gpu/nvptx_compiler.cc:765] The NVIDIA driver's CUDA version is 12.1 which is ol
der than the ptxas CUDA version (12.5.40). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages. number of available cpu:  8
num_io_process should not exceed number of available cpu, reset to  8
/opt/mamba/envs/crystalgpt/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompa
tible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.                                        self.pid = os.fork()
25 Pmm2 5
g, a, w, m, symbol, x: 25 3 4 1 1d 25 Pmm2 5
g, a, w, m, symbol, x: 25 82 4 1 1d [0.5        0.5        0.55085454]
g, a, w, m, symbol, x: 25 14 1 1 1a [0.         0.         0.28531504]
[0.5        0.5        0.50596338]
g, a, w, m, symbol, x: 25 7 2 1 1b g, a, w, m, symbol, x: 25 74 1 1 1a [0.         0.5        0.15366418]
[0.         0.         0.00040354]
g, a, w, m, symbol, x: 25 8 3 1 1c g, a, w, m, symbol, x: 25 7 3 1 1c[0.5        0.         0.47407905] 
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.         0.49964437]
[0.5        0.5        0.03555206]g, a, w, m, symbol, x:
==================================
...
===================================
221 Pm-3m 3
g, a, w, m, symbol, x: 221 29 1 1 1a [0. 0. 0.]
g, a, w, m, symbol, x: 221 33 2 1 1b [0.5 0.5 0.5]
g, a, w, m, symbol, x: 221 7 3 3 3c [0.  0.5 0.5]
['1a' '1b' '3c'] [29 33  7] [1 2 3] 5
===================================
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(21, 119)
Segmentation fault
```

**Reproduction Steps:**
1. Follow the provided bash scripts in order.
2. Observe the error after the corrected script execution.

1. **Environment Activation & GPU Check:**
   ```bash
   conda activate crystalgpt
   ```

2. **CUDA and JAX Version Check:**
   ```bash
   nvcc --version
   ```

3. **JAX Installation:**
   ```bash
   pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
   ```

4. **Requirements Installation:**
   ```bash
   pip install -r requirements.txt
   ```

5. **Model Download & Rename:**
   ```bash
   wget "https://drive.usercontent.google.com/u/0/uc?id=1koHC6n38BqsY2_z3xHTi40HcFbVesUKd&export=download"
   mv downloaded_model_file epoch_003800.pkl
   ```

6. **Initial Script Execution with Error:**
   ```bash
   python /home/CrystalFormer/src/main.py --optimizer none --test_path /home/CrystalFormer/data/mini.csv --restore_path /data/model/epoch_003800.pkl --spacegroup 160 --num_samples 1000 --batchsize 1000 --temperature 1.0 --use_foriloop
   ```

No `--use_foriloop` available.

7. **Corrected Script Execution Resulting in Segmentation Fault:**
   ```bash
   python /home/CrystalFormer/src/main.py --optimizer none --test_path /home/CrystalFormer/data/mini.csv --restore_path /data/model/epoch_003800.pkl --spacegroup 160 --num_samples 1000 --batchsize 1000 --temperature 1.0
   ```

**Notes:**
- The script outputs warnings regarding CUDA version mismatch and potential deadlock before the `Segmentation fault`.

**Attachments:**

```bash
nvidia-smi
Thu Jun 27 16:47:26 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:09.0 Off |                    0 |
| N/A   31C    P0    27W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

**Comment by zdcao121** [comment]
- The `--use_foriloop` parameter has been deprecated, I will update the doc ASAP
- While using `--restore_path`, you just need to specify the path to the folder which contains the parameter file, so you need change `--restore_path /data/model/epoch_003800.pkl` to `--restore_path /data/model/`

**Comment by Osgood001** [comment]
similar error message persists:

```bash
python /home/CrystalFormer/src/main.py --optimizer none --test_path /home/CrystalFormer/data/mini.csv --restore_path /data/model/ --spacegroup 160 --num_samples 1000  --batchsize 1000 --temperature 1.0
2024-06-27 21:19:01.921329: W external/xla/xla/service/gpu/nvptx_compiler.cc:765] The NVIDIA driver's CUDA version is 12.1 which is older 
than the ptxas CUDA version (12.5.40). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.             number of available cpu:  8
num_io_process should not exceed number of available cpu, reset to  8
/opt/mamba/envs/crystalgpt/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatibl
e with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.                                                self.pid = os.fork()
25 Pmm2 5
g, a, w, m, symbol, x: 25 3 4 1 1d [0.5        0.5        0.55085454]
25 Pmm2 g, a, w, m, symbol, x:5 25 
14 1 1 1a g, a, w, m, symbol, x: 25 81 4 1 1d [0.         0.         0.28531504]
g, a, w, m, symbol, x: 25 7 2 1 1b [0.         0.5        0.15366418]
[0.5       0.5       0.5057673]g, a, w, m, symbol, x:
 25 8 3 1 1c g, a, w, m, symbol, x: 25 44 1 1 [0.5        0.         0.47407905]1a 
g, a, w, m, symbol, x: 25 8 4 1 1d [0.         0.         0.00033725]
[0.5        0.5        0.03555206]
g, a, w, m, symbol, x: 25 8 3 1 1c ['1a' '1b' '1c' '1d' '1d'] [14  7  8  3  8][0.5        0.         0.49976346] 
[1 2 3 4 4] 5
g, a, w, m, symbol, x: 25 8 4 1 1d ===================================
[0.5        0.5        0.00473415]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.49946523]
['1a' '1b' '1c' '1d' '1d'] [44  9  8 81  8] [1 2 3 4 4] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 82 4 1 1d [0.5        0.5        0.50596338]
g, a, w, m, symbol, x: 25 74 1 1 1a [0.         0.         0.00040354]
g, a, w, m, symbol, x: 25 7 3 1 1c [0.5        0.         0.49964437]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.00486688]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.49949773]
['1a' '1b' '1c' '1d' '1d'] [74  9  7 82  8] [1 2 3 4 4] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 4 4 1 1d [0.5        0.5        0.58392302]
g, a, w, m, symbol, x: 25 80 1 1 1a [0.         0.         0.95842243]
g, a, w, m, symbol, x: 25 16 2 1 1b [0.         0.5        0.37464796]
25 Pmm2 5
g, a, w, m, symbol, x: 25 8 3 1 1c g, a, w, m, symbol, x: 25 49 4 1 1d [0.5        0.         0.60862477]
g, a, w, m, symbol, x:[0.5        0.5        0.49980599] 25
 8 4 1 1d g, a, w, m, symbol, x: 25 42 1 1 [0.5        0.5        0.97526365]1a
 ['1a' '1b' '1c' '1d' '1d'] [0.         0.         0.00260664]
[80 16  8  4  8] [1 2 3 4 4] 5
g, a, w, m, symbol, x: 25 7=================================== 
3 1 1c [0.5        0.         0.50122382]
g, a, w, m, symbol, x: 25 8 4 1 1d [5.000e-01 5.000e-01 9.054e-05]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.49977465]
['1a' '1b' '1c' '1d' '1d'] [42  9  7 49  8] [1 2 3 4 4] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 83 2 1 1b [0.5        0.5        0.53993421]
g, a, w, m, symbol, x: 99 78 1 1 1a [0.         0.         0.29997257]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.36834345]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.01082605]
['1a' '1b' '1b' '2c'] [78 83  8  7] [1 2 2 3] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 25 1 1 1a [0.         0.         0.18175892]
g, a, w, m, symbol, x: 99 51 2 1 1b [0.5        0.5        0.52701483]
g, a, w, m, symbol, x: 99 8 3 2 2c [0.5        0.         0.43719431]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.00744286]
['1a' '1b' '1b' '2c'] [25 51  8  8] [1 2 2 3] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 14 2 1 1b [0.5       0.5       0.5038645]
g, a, w, m, symbol, x: 99 83 1 1 1a [0.        0.        0.0033032]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.50099633]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.00099404]
['1a' '1b' '1b' '2c'] [83 14  8  7] [1 2 2 3] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 29 1 1 1a [0.         0.         0.29436098]
g, a, w, m, symbol, x: 25 33 4 1 1d [0.5       0.5       0.5496278]
g, a, w, m, symbol, x: 25 16 2 1 1b [0.         0.5        0.30689326]
g, a, w, m, symbol, x: 25 8 3 1 1c [0.5       0.        0.4278454]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.94484628]
['1a' '1b' '1c' '1d' '1d'] [29 16  8 33  8] [1 2 3 4 4] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 37 1 1 1a [0.         0.         0.00153426]
g, a, w, m, symbol, x: 25 23 4 1 1d [0.5        0.5        0.50873207]
g, a, w, m, symbol, x: 25 7 3 1 1c [0.5        0.         0.50282254]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.99597578]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.50025732]
['1a' '1b' '1c' '1d' '1d'] [37  9  7 23  8] [1 2 3 4 4] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 80 1 1 1a [0.         0.         0.00191037]
g, a, w, m, symbol, x: 99 51 2 1 1b [0.5        0.5        0.50332499]
g, a, w, m, symbol, x: 99 8 3 2 2c [0.5        0.         0.50101089]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5       0.5       0.0031116]
['1a' '1b' '1b' '2c'] [80 51  8  8] [1 2 2 3] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 55 1 1 1a [0.         0.         0.97413323]
g, a, w, m, symbol, x: 25 79 4 1 1d [0.5        0.5        0.56910341]
g, a, w, m, symbol, x: 25 16 2 1 1b [0.         0.5        0.44763128]
g, a, w, m, symbol, x: 25 8 3 1 1c [0.5        0.         0.50469533]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.00702974]
['1a' '1b' '1c' '1d' '1d'] [55 16  8 79  8] [1 2 3 4 4] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 28 2 1 1b [0.5        0.5        0.52373828]
g, a, w, m, symbol, x: 99 50 1 1 1a [0.         0.         0.12294783]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.40141303]
g, a, w, m, symbol, x: 99 7 2 1 1b [0.5        0.5        0.97933654]
['1a' '1b' '1b' '2c'] [50 28  7  7] [1 2 2 3] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 23 1 1 1a 221 Pm-3m 3
g, a, w, m, symbol, x: 221 29 1 1 1a [0.         0.         0.00049375]
[0. 0. 0.]
g, a, w, m, symbol, x: 25 45 4 1 1d g, a, w, m, symbol, x: 221 33 2 1 1b [0.5        0.5        0.50448113]
g, a, w, m, symbol, x: 25 7 3 1 1c [0.5 0.5 0.5]
g, a, w, m, symbol, x: 221 7 3 3 3c [0.  0.5 0.5]
['1a' '1b' '3c'] [29 33  7] [1 2 3] 5
===================================
[0.5        0.         0.49968514]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.00455817]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.49993299]
['1a' '1b' '1c' '1d' '1d'] 99 P4mm 4
[23  9  7 45  8] [1 2 3 4 4] 5
g, a, w, m, symbol, x: 99 44 2 1 1b [0.5       0.5       0.5020085]
g, a, w, m, symbol, x: 99 82 1 1 1a [0.         0.         0.00946453]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.50031472]
===================================
g, a, w, m, symbol, x: 99 7 2 1 1b [0.5        0.5        0.99922009]
['1a' '1b' '1b' '2c'] [82 44  7  7] [1 2 2 3] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 31 2 1 1b [0.5        0.5        0.50551749]
g, a, w, m, symbol, x: 99 45 1 1 1a [0.         0.         0.00042918]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.49964712]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.00457519]
['1a' '1b' '1b' '2c'] [45 31  8  7] [1 2 2 3] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 55 1 1 1a [0.         0.         0.00029164]
g, a, w, m, symbol, x: 99 37 2 1 1b [0.5        0.5        0.50369172]
g, a, w, m, symbol, x: 99 799 P4mm 4
 3 2 2c [0.5        0.         0.50008052]
g, a, w, m, symbol, x:g, a, w, m, symbol, x:  9999  407  22  11  1b1b  [0.5       0.5       0.0053311][0.5        0.5        0.50628152]
g, a, w, m, symbol, x: 99 50 1 1 1a 
['1a' '1b' '1b' '2c'] [55 37  7  7] [1 2 2 3] 5
===================================
[0.         0.         0.00112253]
g, a, w, m, symbol, x: 99 8 3 2 2c [0.5        0.         0.49983605]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5       0.5       0.0031409]
['1a' '1b' '1b' '2c'] [50 40  8  8] [1 2 2 3] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 22 2 1 1b [0.5        0.5        0.50503093]
g, a, w, m, symbol, x: 99 31 1 1 1a [0.         0.         0.00052032]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.49997047]
g, a, w, m, symbol, x: 99 7 2 1 1b [0.5        0.5        0.00426856]
['1a' '1b' '1b' '2c'] [31 22  7  7] [1 2 2 3] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 22 1 1 1a [0.         0.         0.60921094]
g, a, w, m, symbol, x: 25 76 4 1 1d [0.5        0.5        0.77619935]
g, a, w, m, symbol, x:25 25 7 3 1 1c  Pmm2 5
g, a, w, m, symbol, x: 25 57 4 1 1d [0.5        0.5        0.50511685][0.5       0.        0.7420008]
g, a, w, m, symbol, x: 25 8 4 1 1d 
g, a, w, m, symbol, x: 25 73 1 1 1a [0.         0.         0.00056845]
g, a, w, m, symbol, x: 25[0.5        0.5        0.23143281]
 7 3 1 1c g, a, w, m, symbol, x: 25 9 2 1 1b [0.       0.5      0.415284]
[0.5        0.         0.50024548]
['1a' '1b' '1c' '1d' '1d'] g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.00500002]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.49949325]
['1a' '1b' '1c' '1d' '1d'] [73  9  7 57  8] [1 2 3 4 4] 5
===================================
[22  9  7 76  8] [1 2 3 4 4] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 4 1 1 1a [0.         0.         0.46427455]
g, a, w, m, symbol, x: 99 33 2 1 1b [0.5        0.5        0.28508148]
g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.39177199]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.81772798]
['1a' '1b' '1b' '2c'] [ 4 33  8  7] [1 2 2 3] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 19 1 1 1a 99 P4mm 4
g, a, w, m, symbol, x: 99 27 2 1 1b [0.         0.         0.00055819]
[0.5        0.5        0.53485591]
g, a, w, m, symbol, x: 99 75 1 1 1a g, a, w, m, symbol, x: 99 [0.         0.         0.17877368]
g, a, w, m, symbol, x:38 99 7 3 2 2c  2 1[0.5        0.         0.43333029]
 1b g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.00460981]
['1a' '1b' '1b' '2c'] [75 27  8  7] [1 2 2 3] 5
===================================[0.5        0.5        0.50549028]

g, a, w, m, symbol, x: 99 7 3 2 2c [0.5        0.         0.49974383]
g, a, w, m, symbol, x: 99 8 2 1 1b [0.5        0.5        0.00524112]
['1a' '1b' '1b' '2c'] [19 38  8  7] [1 2 2 3] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 56 1 1 1a [0.         0.         0.00096878]
g, a, w, m, symbol, x: 25 44 4 1 1d [0.5        0.5        0.50393304]
g, a, w, m, symbol, x: 25 8 3 1 1c [0.5        0.         0.50006739]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.00410809]
g, a, w, m, symbol, x: 25 9 2 1 1b [0.         0.5        0.50043428]
['1a' '1b' '1c' '1d' '1d'] [56  9  8 44  8] [1 2 3 4 4] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 39 1 1 1a [0.         0.         0.91067428]
g, a, w, m, symbol, x: 25 49 4 1 1d [0.5        0.5        0.57043078]
g, a, w, m, symbol, x: 25 16 2 1 1b [0.         0.5        0.36299416]
g, a, w, m, symbol, x: 25 8 3 1 1c [0.5        0.         0.69224078]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.04031656]
['1a' '1b' '1c' '1d' '1d'] [39 16  8 49  8] [1 2 3 4 4] 5
===================================
99 P4mm 4
g, a, w, m, symbol, x: 99 27 2 991  1bP4mm  4
g, a, w, m, symbol, x: 99 72[0.5        0.5        0.43551539] 2
 1 1b g, a, w, m, symbol, x: 99 74 1 1 1a [0.        0.        0.0935678]
g, a, w, m, symbol, x: 99 8 3 2 2c [0.5        0.5        0.52762345]
g, a, w, m, symbol, x: 99 13 1 1 1a [0.5        0.         0.36321747]
[0.         0.         0.23811871]
g, a, w, m, symbol, x:g, a, w, m, symbol, x:  9999  88  23  12  1b2c  [0.5        0.5        0.92262586]
['1a' '1b' '1b' '2c'] [74 27  8  8] [0.5        0.         0.41935511]
g, a, w, m, symbol, x: 99 8[1 2 2 3] 2  51
 1b ===================================
[0.5        0.5        0.99443926]
['1a' '1b' '1b' '2c'] [13 72  8  8] [1 2 2 3] 5
===================================
221 Pm-3m 3
g, a, w, m, symbol, x: 221 3 2 1 1b [0.5 0.5 0.5]
g, a, w, m, symbol, x: 221 13 1 1 1a [0. 0. 0.]
g, a, w, m, symbol, x: 221 8 4 3 3d [0.5 0.  0. ]
['1a' '1b' '3d'] [13  3  8] [1 2 4] 5
===================================
25 Pmm2 5
g, a, w, m, symbol, x: 25 4 4 1 1d [0.5        0.5        0.50295577]
g, a, w, m, symbol, x: 25 33 1 1 1a [0.         0.         0.18006878]
g, a, w, m, symbol, x: 25 7 2 1 1b [0.         0.5        0.42020007]
g, a, w, m, symbol, x: 25 8 3 1 1c [0.5        0.         0.42690466]
g, a, w, m, symbol, x: 25 8 4 1 1d [0.5        0.5        0.94932273]
['1a' '1b' '1c' '1d' '1d'] [33  7  8  4  8] [1 2 3 4 4] 5
===================================
221 Pm-3m 3
g, a, w, m, symbol, x: 221 19 2 1 1b [0.5 0.5 0.5]
g, a, w, m, symbol, x: 221 51 1 1 1a [0. 0. 0.]
g, a, w, m, symbol, x: 221 8 4 3 3d [0.5 0.  0. ]
['1a' '1b' '3d'] [51 19  8] [1 2 4] 5
===================================
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(21, 119)
Segmentation fault

```

**Comment by zdcao121** [comment]
- maybe the `cuda12.1` is incompatible with the latest version of `jax`, you need try newer version of cuda like `cuda12.5`
- the way you used to install `jax` has been deprecated. Please see the new [ installation guide](https://jax.readthedocs.io/en/latest/installation.html) of `jax`

**Comment by Osgood001** [comment]
Thanks! Already fixed by switching to `cuda12.5` and re-install jax!
